#!/bin/bash

if (command -v atuin) ; then
  eval "$(atuin init zsh)"
fi
export PATH="$PATH:$HOME/.cargo/bin/"

export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"

alias mydebugpy="python -m debugpy --listen 5678 --wait-for-client"

export PATH="$HOME/.local/bin:$PATH"

. "$HOME/.cargo/env"